sudo: required
services:
  - docker

script:
  - docker build -t llcawthorne/react-example .
  - docker images llcawthorne/react-example

before_deploy:
  - docker login -u llcawthorne -p password

deploy:
  provider: script
  script: docker push llcawthorne/react-example
  on:
    branch: master