version: '3.5'

services:
  react-app:
    container_name: app-react
    build: 
      context: .
      dockerfile: Dockerfile
    volumes:
      - '.:/user/src/app'
      - '/usr/src/app/node_modules'
    ports:
      - '3000:3000'
    environment:
      - NODE_ENV=development
